### ISSUE TITLE
Can't load image with special tokens

### ISSUE THREAD

**Issue by LittlePoolSpirit** [Vision-CAIR/artelingo#2]
I have tried to use the 'image_file' field of 'artelingo_release.csv'.
But because of the special token in name of image. The program told me that couldn't find the corresponding file.

same cases like this
![image](https://github.com/Vision-CAIR/artelingo/assets/103354177/5a624a18-2b6a-4bb7-8324-5dcc425f005b)

Can anyone provide some solution?

**Comment by LittlePoolSpirit** [comment]
> I have tried to use the 'image_file' field of 'artelingo_release.csv'. But because of the special token in name of image. The program told me that couldn't find the corresponding file.
> 
> same cases like this ![image](https://user-images.githubusercontent.com/103354177/265696956-5a624a18-2b6a-4bb7-8324-5dcc425f005b.png)
> 
> Can anyone provide some solution?

Well, I found a very stupid way to slove the problem

**Comment by amith-ananthram** [comment]
For others, you can determine the unicode form of your filenames on disk with:

```
unicodedata.is_normalized('NFC' or 'NFD' or 'NFKC' or 'NFKD', 'disk/file/name') 
```

The ArtELingo dataset uses NFD.  If your disk uses something different, you can re-normalize ArtELingo's filenames using:

```
unicodedata.normalize('NFC' or 'NFD' or 'NFKC' or 'NFKD', 'disk/file/name') 
```

And that should let you read your version.  More here: https://docs.python.org/3/library/unicodedata.html#unicodedata.normalize
